# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the trunk branch
  # push:
  #   branches: [ trunk ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile with Maven
        run: echo This would eventually compile with maven!

      # Runs a set of commands using the runners shell
      - name: Write WAR file to chrondev
        run: |
          echo This would scp the war file to dev
          echo ssh in to chrondev and backup the prev war
          echo then deploy the new war
      
      # Runs a set of commands using the runners shell
      - name: Tell us which runner you are on...
        run: |
          hostname
          ssh -T ansible@chrondev hostname
          ssh -T ansible@chrondev uptime
